name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y qt5-qmake qt5-default build-essential
    - name: Generate Makefile with qmake
      run: qmake Network_Interfaces.pro -o Makefile
    - name: Build
      run: make
