name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y qt5-qmake qt5-default
    - name: Generate Makefile with qmake
      run: qmake Network_Interfaces.pro
    - name: make
      run: make
    - name: make check
      run: make check
